export const ActionType = {
  //Categories
  FETCH_CATEGORY_LIST: "FETCH_POST_LIST",
  FETCH_CATEGORY_LIST_SUCCESS: "FETCH_POST_LIST_SUCCESS",
  FETCH_CATEGORY_LIST_FAILED: "FETCH_POST_LIST_FAILED",
  UPDATE_NEW_CATEGORYTYPE: "UPDATE_NEW_CATEGORYTYPE",
  //Carts
  ADD_TO_CART: "ADD_TO_CART"
};
